"""brg.numerical.gpu : A package for using the GPU for numerical computation."""

docs = [
    {'array':
        [
        'get',
        'give',
        'ones',
        'random',
        'tile',
        'zeros',
        'diag',
        'eye'
        ]
    },
    {'math':
        [
        'abs',
        'asin',
        'acos',
        'atan',
        'cos',
        'cosh',
        'sin',
        'sinh',
        'tan',
        'tanh',
        'sqrt',
        'sum',
        'mean',
        'log10',
        'log',
        'exp',
        'floor',
        'ceil',
        'argmax',
        'argmin',
        'max',
        'min'
        ]
    },
    {'linalg':
        [
        'det',
        'conj',
        'normrow',
        'transpose',
        'trace',
        'dot',
        'cross',
        'hermitian',
        'inv',
        'pinv',
        'eig',
        'svd'
        ]
    },
    {'utilities':
        [
        'device'
        ]
    }
]
