docs = [
    {'array': ['get',
               'give',
               'ones',
               'random',
               'tile',
               'zeros',
               'diag']},
    {'math': ['abs',
               'asin',
               'acos',
               'atan',
               'cos',
               'cosh',
               'sin',
               'sinh',
               'tan',
               'tanh',
               'sqrt',
               'sum',
               'mean',
               'log10',
               'log',
               'exp',
               'floor',
               'ceil']},
    {'linalg': ['det',
                'conj',
                'normrow',
                'transpose',
                'trace',
                'dot',
                'cross',
                'hermitian',
                'inv',
                'pinv']},
    {'utilities': ['device']}
]
