"""brg.numerical : A package for numerical computation."""

docs = [
    {'gpu': []},
    {'methods': []},
    {'solvers': []},
	{'geometry':
        [
        'lengths'
        ]
    },
    {'linalg':
        [
        'rank',
        'dof',
        'normrow',
        'normalizerow',
        'rot90',
        'chofactor',
        'lufactorized',
        'solve_with_known',
        'spsolve_with_known',
        'nullspace',
        'rref',
        'pivots',
        'nonpivots'
        ]
    },
    {'matrices':
        [
        'connectivity_matrix',
        'mass_matrix',
		'equilibrium_matrix',
		'laplacian_matrix'
        ]
    },
    {'operators':
        [
        'grad'
        ]
    },
    {'preconditioning':
        [
        ]
    },
	{'spatial':
        [
        'closest_points_points',
        'project_points_heightfield',
        'bounding_box_2d',
        'bounding_box_3d'
        ]
    },
    {'statistics':
        [
        'principal_component_analysis'
        ]
    },
	{'utilities':
        [
        'float_formatter',
		'set_array_print_precision',
		'unset_array_print_precision'
        ]
    },
	{'xforms':
        [
        'translation_matrix',
        'scale_matrix',
        'rotation_matrix'
        ]
    }
]
